### ISSUE TITLE
Merge order for change of package name

### ISSUE THREAD

**Issue by jhprinz** [choderalab/openpathsampling#139]
In what order should we merge?

- ToyStore
- NewPackageName
- NewPathMover

**Comment by dwhswenson** [comment]
Add to the list:

* RETIS
* Minus

My suggestion:
1. RETIS
2. Toy
3. Minus
4. NewPackageName
5. NewPathMover

I'll move the storage problem to Minus instead of RETIS; then RETIS can be merged now. Aside from that, Minus is mainly a matter of testing now. NewPathMover will have to be after RETIS and Minus, since it will be easiest to modify those to the new path movers at the same time. NewName can go anywhere. I put it there kind of arbitrarily. NewPathMover requires it; nothing else does, right?

**Comment by jhprinz** [comment]
Sounds good.

Right, I put newpathmover after the newnamechange since I wasn't sure if I could come up with something useful. If it works as expected this will enable the new storage and require to make all movers output the MovePath instead of only the samples. I can do that, once Minus and the the rest is in.

**Comment by jhprinz** [comment]
Closing this, since we only have to merge newpathmover left.
