### ISSUE TITLE
Disallow calling abstract methods

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/openpathsampling#299]
We have a few classes (`PathMover`, `Ensemble`, `VolumeEnsemble`, and I'm sure others) which, if we were implementing this in C++, would be abstract classes. Core Python doesn't have the concept of abstract classes; any class can be instantiated.

Currently, we do some things that aren't very correct; namely, returning reasonable values for abstract methods that need to be overridden by subclasses. If a user were to instantiate an `Ensemble` (instead of a subclass), they would get something which might be called the "infinite-length trajectory ensemble": `__call__` always returns false, while `can_append` and `can_prepend` always return true.

I suspect that if a user instantiates `Ensemble`, it was probably an accident. I think it is extremely unlikely that the user wants this infinite-length trajectory ensemble. Since this is almost certainly user error, I think it makes sense to raise an error. In addition, raising errors will make it less likely for developers to forget to implement some function (e.g., imagine what would happen if a dev implemented an ensemble, but only overrode `call` and `can_append`, forgetting `can_prepend`: code would run without error, and without careful testing, the naive developer might put bad code into production!)

We should do one of the following:

* abstract methods return `NotImplementedError`
* use the `abc` (abstract base class) module to forbid instantiation of abstract classes.

I think either option is reasonable. Using `NotImplementedError` would be easier to do (using `abc` will definitely require some modifications of the tests, and I'm not sure what effect it might have on storage). On the other hand, using `abc` makes easier for developers to catch unimplemented functions. Note that even if we use `abc`, some aspects should probably still raise `NotImplementedError` (e.g., `Ensemble.oom_matrix`, which isn't *required* in order to do path sampling, but may be required for certain analyses). 

Thoughts?

**Comment by jhprinz** [comment]
In general a must to avoid stupid mistakes. I am not sure what I prefer, although I assume that in the derived classes we use some functionality of the abstract base class. Just adding `NotImplementedError`  will break some of the functionality and I assume that `abc` can cope with this more elegantly. In the worst case we have to reimplement a canonical behavior in all derived classes. 

If I read the documentatin from `abc` correctly, you cannot call super to run initialization code from abstract classes. So, we need to make sure that there is no problem.

Concerning the OPSObject this might be a problem since we now require all base classes to be subclasses of OPSObject and all of these need to call super initialization. This would mean that the 
`NotImplemented` approach is easier to deal with given the current storage. 

A third (less thorough) option would be to hide the base classes from the user and not include them in the `__init__.py` file. This means you can still instantiate the base class, but only if you specifically load the function into your namespace. Otherwise you cannot access it.

The third option combined with the `NotImplementedError` would be my current approach.

Last thought might be to change the baseclass to the `Full` - ensemble/volume, etc... and let everything derive from the full ensemble (which it is right now).

**Comment by dwhswenson** [comment]
> The third option combined with the NotImplementedError would be my current approach.

Agreed. Abstract classes are accessible as, e.g., `openpathsampling.ensemble.Ensemble`, but not as `openpathsampling.Ensemble`. And if you try to use it, it will raise `NotImplementedError` as soon as, e.g., you try to get either `.can_append` or `.__call__`.

I think this is the best/easiest approach. "Hiding" them from quick accessibility is a nice way to make it less likely that someone will accidentally use it. ABCs might allow for a fancier treatment that `NotImplementedError`, but there might be undesired side effects, especially around storage.

All sounds good to me!

> Last thought might be to change the baseclass to the Full - ensemble/volume, etc... and let everything derive from the full ensemble (which it is right now).

I don't like this one. `empty = paths.EmptyVolume(); assert(isinstance(empty, FullVolume()))` : that should not pass.

**Comment by jhprinz** [comment]
Good. Then let's do it this way...

> I don't like this one. empty = paths.EmptyVolume(); assert(isinstance(empty, FullVolume())) : that should not pass.

Well, true, that does look weird...

**Comment by dwhswenson** [comment]
One other option to consider here: would it make sense to use a `paths.abstract` namespace for the base classes for when users explicitly want those? So `paths.abstract.PathMover` and `paths.abstract.Ensemble` instead of `paths.pathmover.PathMover` and `paths.ensemble.Ensemble`.

Not sure what advantages/disadvantages might exist in this approach, just tossing it out for consideration.

Implementation is trivial -- just a directory containing only the appropriate `__init__.py`.

**Comment by dwhswenson** [comment]
This was resolved by #375.
