### ISSUE TITLE
WHAM possible isufficient data errer

### ISSUE THREAD

**Issue by jhprinz** [choderalab/openpathsampling#303]
I just discovered a potential bug in using WHAM. I ran the MSTIS notebooks and in state C
in the outermost interface all 16 trajectories had a max_lambda > 0.48. I assume that all trajectories will cross to another state, but still apparently my binning had a too small cutoff. The result is that
the cumulative function contains only 1.0 which is of course correct. But this causes the 
`self.pre_guess` to return too little values as an initial guess in my case 3 instead of 4 values and so the initial solution for the WHAM has only 2 values instead of 3.

In my understanding the correct solution would be somehow increase this array with the max_lambda values until it has the proper size. But I am not sure if that leads to problems for WHAM. 

It seems that in some cases this causes the test to fail. Would it be possible to add a fail save or do we need to make the data generation better?

**Comment by dwhswenson** [comment]
If I'm understanding correctly, the problem is that your histogram parameters (`hist_args` or something like that) are wrong -- specifically, you have the wrong maximum value of lambda.

The main background point to keep in mind here is that the crossing probability histograms for each interface, used as input to WHAM, must have the same discretization: they must have both the same total range and the same bin size.

With the current histogram routine, you must provide the maximum lambda for binning, as well as the bin width. This is because we're currently wrapping the `numpy` histogram function.

I would like to eventually replace this with a histogram routine that only requires bin width and one bin edge as input. Currently we say "make a histogram of the data, assuming all data points are between `min` and `max`, with bin width `w`." I would like to instead say, "make a histogram of this data, with one bin divider at `min` and bin width `w`." I wrote a C++ program to do this when I was dealing with a multidimensional sparse histogram: the problem there is that many histogram volumes are empty, but that solution will also solve this problem, because it will dynamically adjust each 1D histogram to have the correct range.

From there, it is easy to make all the histograms have the same discretization: any bin that is occupied in any histogram should be in all histograms; if the bin wasn't there already, it gets added with count 0. All of this would be in pre-processing before the WHAM script. (I suspect this same problem could appear with other histogram-combining approaches like MBAR and TRAM: if your input histograms don't cover the relevant range, it's garbage in, garbage out.)

If I understand the issue correctly, this would solve your problem, have no additional computational cost, and it would also make user input a little easier -- just tell the bin width and (optionally) one of the bin edges (choose 0 if no edge given), instead of needing to figure out what the maximum relevant value of lambda is. 

I'd call that the optimal solution.

However, I'm planning to put that together after version 1.0, for the following reasons:

1. This problem only occurs because either (a) you have extraordinarily bad sampling (you started with a trajectory that went to the final state, and never fully equilibrated), (b) your histogram arguments have a bad maximum lambda, or (c) you have a wasteful interface (one that actually does have every single path go into the final state). All three of these problems are easily fixed:
  - Bad sampling: sample longer (and none of your results are trustworthy yet)
  - Bad histogram arguments: change them, and re-run analysis with `force=True`. No need to resample.
  - Wasteful interface: here's where I need to add more documentation, but I'm pretty sure this can be handled by removing the offending interface from its "analysis transition" in the network. Again, no need to resample.

2. This is almost never a problem for regular users. In practice, while getting preliminary data for a new system, you need to check whether your crossing probability histograms are any good (because you need to check whether your choice of interfaces was good). This problem will be very obvious while you're doing that.
 
3. (Totally selfish) I wanted to use that as an opportunity to learn how to interface C++ and Python. So it will take some time and effort for me to do. :-)

***

One question: is this causing an actually error to be raised, or is this just giving bad results? If the former, I should definitely add an error message to explain what's going on. If the latter, we might still add a check that writes a message with `logger.warning`.

**Comment by jhprinz** [comment]
Good, then I was at least partially right in my assumption about a too narrow binning. I thought there is a quick fix but then I will just let it the it is. If this is not a real problem I will not worry about it.
