### ISSUE TITLE
Use MBAR instead of WHAM

### ISSUE THREAD

**Issue by jhprinz** [choderalab/openpathsampling#306]
We talked about replacing the use of WHAM with the pyMBAR package at some point. I think that we are now far enough to do so.

**Comment by dwhswenson** [comment]
I think at some point we should try a comparison of WHAM / MBAR / TRAM / path-type analysis / any other approaches we have to analyze TIS-sampled data to obtain rates. But until then, I don't think this is a priority. This doesn't need to be in 1.0.

**Comment by jchodera** [comment]
I have some nontrivial interest in using MBAR (instead of WHAM) to estimate
the TPE.  I think this is a simple change but a significant advancement.

Nobody should be using WHAM.  Histogram estimation techniques are probably
suboptimal.

**Comment by jchodera** [comment]
s/probably/provably/

**Comment by jhprinz** [comment]
I don't see a problem to support both also for comparison. David made this so modular that you could easily plug in pyMBAR support (provided you have installed it).

**Comment by franknoe** [comment]
Isn't MBAR just WHAM in your case since you have discrete states in your 
ensemble?

Am 18/09/15 um 16:41 schrieb Jan-Hendrik Prinz:
>
> I don't see a problem to support both also for comparison. David made 
> this so modular that you could easily plug in pyMBAR support (provided 
> you have installed it).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/choderalab/openpathsampling/issues/306#issuecomment-141472177>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by jhprinz** [comment]
Solved this and also found a new way to directly compute the `f_k` without iteration. See PR #353 .

**Comment by jhprinz** [comment]
Will close this and continue in Issue #353 .
