### ISSUE TITLE
Update examples/ipython/README.md to index example notebooks

### ISSUE THREAD

**Issue by jchodera** [choderalab/openpathsampling#344]
The `README.md` in `examples/ipython/` doesn't index the notebooks in this director, and the filenames are too cryptic to understand what they do.  

Can you update the `README.md` to index these, and maybe also provide links to the master github versions?

**Comment by dwhswenson** [comment]
I mentioned that I had a long thing written up on my thoughts around some of this: here it is, only slightly edited for renamed files:

***

As we get closer to release, I think we should reconsider some of our ipynb integration tests. We also need to clean up the ipynbs we add to the website documentation. Here's the separation I propose; in short, I see the first-tier examples as something where a new user will read/work through all of them, and the second-tier examples as a long list to make sure Google can help people find all sorts of other information. Tests are, obviously, just the things necessary for integration testing. Finally, there are real-world examples, which are exactly that: that actual scripts used to obtain publishable results.

#### First-Tier Examples

These are the examples of how a real user will use OPS -- the first tutorials to walk through. That would be longer versions of `mstis_bootstrap`, `mstis`, `mstis_analysis`, `mistis`, `mistis_analysis`, and some version of the `alanine`. We should keep this list as small as possible: this is what an absolute beginner needs to see. I've also been working on a `troubleshooting` notebook that will probably go here.

This might also include various notebooks that describe more detailed usage, such as the notebooks about `move_schemes_and_strategies` and `transitions_and_networks`, although these might also go to the second tier.

#### Second-Tier Examples

Here's where we show various other features. Things like `sliced_sequential_ensembles` and `langevin_integrator`. The current `toy_tis` and `toy_analysis` might go here, too (better examples for real-world use will be based on networks). These notebooks are more background documentation than tutorial.

#### Tests

Mostly, this will be things like the first-tier examples (but shorter runs). Proper integration tests.

#### Real-World Examples

It might be nice for us to toss up some notebooks that we used in real calculations. In particular, I think everything we use to generate the results for these first papers should go somewhere. And I'm in favor of letting that be a location where we -- or users -- have the option of adding any scripts/notebooks they created for their own papers.

In general, contributing to this is, of course, completely optional: there are plenty of reasons not to share the ugly way the sausage was made. But I think these first papers about the code should be held to a higher standard when it comes to code friendliness, so we should share those. And if I have later papers where I feel good about releasing my scripts, I'd like to do share those scripts and let them benefit our users.

***

Another thought on this: I think the first-tier examples (and tests) should be few enough that they don’t need any further organization. For the other categories, my suggestion is we dump them all onto one main index page for each category. Deeper organization will take lots of time to maintain, and I don’t think it will help our users: at least, I think I’d be more likely to find the specific topic using Google and/or my browser’s "Find…" function to search in the page. A nested structure reduces discoverability.

**Comment by dwhswenson** [comment]
Another comment here: my suggestion for a first tutorial is the MSTIS sequence (`mstis_bootstrap`, `mstis`, `mstis_analysis`). I've been putting documentation into those with the thought that those would be written for people with little experience with TIS and no experience with OPS. They don't require an OpenMM background either. So it would be good to highlight those as the first place to start.

**Comment by jchodera** [comment]
* The proposed organization sounds good, but still does not obviate the need for *writing a README that indexes the files in this directory right now*, before tackling the reorganization
* Should integration tests really be IPython notebooks?  Shouldn't they just be Python nosetests?

**Comment by dwhswenson** [comment]
> The proposed organization sounds good, but still does not obviate the need for writing a README that indexes the files in this directory right now, before tackling the reorganization

Agreed -- my first comment was something I had already written months ago and expected to post when we were cleaning up for release. But since this issue came up, it seemed relevant to include the perspective.

(@jhprinz self-assigned this, so I'm *posting* my thoughts rather than *implementing* them --  I would have taken this one if he hadn't called it first!)

My second comment was more specific to the question of the README (but also relevant to the broader documentation) -- I'm trying to write those notebooks under the assumption that the reader has read one of the @bolhuis & Dellago reviews, but has little other experience with path sampling. I think they're a good place to start, and should be pointed to by both the README and the main sphinx documentation.

> Should integration tests really be IPython notebooks? Shouldn't they just be Python nosetests?

We've been taking the approach that large scale integration tests are in IPython, and unit tests are done in nosetests. @jhprinz's `ipynbtest.py` makes IPython notebooks into a good integration testing platform. The really nice part about this is that *our documentation is tested*. The same notebooks that we use for tutorials are part of the nightly builds. (I can't count how many times I've banged my head against a wall because of outdated documentation.)

In the near future, I think we'll change the tests a bit so that the analysis notebooks call in some file pulled in externally. That will allow us to run ~100 steps in the integration steps, instead of needing 250-300 to ensure that the analysis has sufficient data.

**Comment by jhprinz** [comment]
Started a PR #348 to get a first updated README.md and go from there.

**Comment by jchodera** [comment]
Thanks!

**Comment by jhprinz** [comment]
Can we close this? There is now a README.md file. I would create a new issue about the actual examples we want to keep, etc. We will have to do that right before release anyway I think.

**Comment by dwhswenson** [comment]
README links that do not work:

* storage_tutorial.ipynb
* multistate_system_setup.ipynb

**Comment by jhprinz** [comment]
Okay, do we keep this under "There are so many things in documentation to be fixed before release and this is just one" or is it important to have a separate issue. Then it makes sense to fix this quickly.

**Comment by dwhswenson** [comment]
I'd say this is worth a quick PR. I think you removed `multistate_system_setup` and renamed `storage_tutorial` to `tutorial_storage`, so that's all that need to be done. I'll start a PR for this.

**Comment by jhprinz** [comment]
Thanks for taking care of this.
