### ISSUE TITLE
Improvements to user experience

### ISSUE THREAD

**Issue by dwhswenson** [choderalab/openpathsampling#352]
I was adding some more documentation to the example notebooks, and there are a few convenience functions we might add. (Some I thought of today, some were already marked as "TODO" in the notebook.) @jhprinz, let me know what you think of these:

* `network.sampling_ensembles`: `sum([t.ensembles for t in self.sampling_transitions], [])` -- see `mstis.ipynb` for usefulness
* `sampleset.append_new(sample)`: takes the given sample, and adds a sample with that ensemble and trajectory, and with replica ID equal `max([s.replica for s in self.samples])+1`. Very useful for setting up initial sample sets.
* `storage.sync_all()`: just a convenience for `storage.sync(); storage.cvs.sync()`

Unless there's opposition, I'll implement these in a quick little PR.

**Comment by jhprinz** [comment]
- `storage.sync_all()`: We should definitely have something like that. This is probably better than just overriding `storage.sync()` because you might want to only sync the storage without always calling `st.cvs.sync()`

- `sampleset.append_new(sample)`: Only thing I though is that `replica` could be in the method name to make clear that we do something with replica. Maybe `add_new_replica` or only `new_replica` or `add_replica` ? Just a suggestions. The function is definitely useful.

- `network.sampling_ensembles`: Very useful. Does it make sense to add a `list(set(...))` to make the list unique?

**Comment by dwhswenson** [comment]
> Only thing I though is that replica could be in the method name to make clear that we do something with replica. Maybe `add_new_replica` or only `new_replica` or `add_replica` ?

Good point. I like `add_new_replica`.

> Does it make sense to add a `list(set(...))` to make the list unique?

Hmm... maybe, but maybe not. In practice, I can't imagine a situation where the list wouldn't already be single-occurrence. But if it wasn't, the user might want to know/use that information, so let's not hide it. The user can always directly use the `list(set(...))` wrapping if needed.

I'll get on this one, and issue a PR for it tonight or tomorrow.

**Comment by dwhswenson** [comment]
@jhprinz : Regarding `storage.sync_all()`: if, for some reason, `self.cvs` doesn't exist, should this raise an error or not?

**Comment by dwhswenson** [comment]
`network.sampling_ensembles` : Apparently I *had* implemented this, but I called it `transition_ensembles`. That was poorly named, because we have "sampling transitions" (in the list `network.sampling_transitions`) and "analysis transitions", where the analysis transitions are in the dictionary `network.transitions`.

Renaming it to `network.sampling_ensembles`.

**Comment by jhprinz** [comment]
> @jhprinz : Regarding storage.sync_all(): if, for some reason, self.cvs doesn't exist, should this raise an error or not?

Hmm, that would be bad, if it would not exist. Point is that in the current implementation the set of object_stores is hard coded. I want to make this also part of the storage, so that you can just open a store and it opens all the objects that you have. This is necessary for external snapshot support and the better naming that I dream about...

Anyway. Right now if it does not exist the user has done something very bad. In theory the constructor calls something like
```
self.cvs = paths.CV_Store(params...)
```
and if that object does not exist this is a bug. In the new implementation (in the future) this could happen) and I would just ignore it for syncing means to sync all that can be synced and if you open a store that does not support cvs, then I think sync should ignore it. The normal sync work the same. It syncs all variables to disk that are there.
I would write it to log though.

**Comment by dwhswenson** [comment]
What I had been doing was to silence the (potential) error in a `try: except AttributeError`. I'll just remove that, and if it raises the AttributeError, it won't silence it.

**Comment by dwhswenson** [comment]
> I like `add_new_replica`.

Actually, in the end I went with `append_as_new_replica`.
