### ISSUE TITLE
Find issue in MSTIS notebook

### ISSUE THREAD

**Issue by bolhuis** [choderalab/openpathsampling#361]
I am trying to get to grips with the mstis notebook, and prepare for tps. I do this by changing the 3 well  potential to a 2 well potential. This reduces the number of states to A and B.
Bootstrapping works. However I get the following problems:

stateA = old_store.volumes.find('A')[0]
stateB = old_store.volumes.find('B')[0]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-21-5ffa48458735> in <module>()
----> 1 stateA = old_store.volumes.find('A')[0]
      2 stateB = old_store.volumes.find('B')[0]

/Users/bolhuis/git/openpathsampling/openpathsampling/storage/object_storage.pyc in find(self, name)
    221                 self.update_name_cache()
    222 
--> 223             return self[self.name_idx[name]]
    224 
    225         return []

KeyError: 'A'

It seems as if the state cannot be found in the old volume.
This is very strange, as the 3 well systems works fine.
I circumvented this problem by setting explicitly:

stateA = paths.CVRangeVolume(opA, 0.0, 0.2**2)
stateB = paths.CVRangeVolume(opB, 0.0, 0.2**2)

which is a bit dumb of course, but works.

However, the first approach should also work. Can you look in to this?

**Comment by dwhswenson** [comment]
Try the following:

```python
for volume in old_store.volumes:
    print volume.name
```

This will tell you the names of all volumes saved to storage.

**Comment by bolhuis** [comment]
When I try I get this: 

all states except B
0.0<opA<0.04
[UnionVolume]
B
[UnionVolume]
0.0<opA<0.09
[UnionVolume]
[UnionVolume]
0.0<opA<0.16
[UnionVolume]
[UnionVolume]
0.0<opA<0.25
[UnionVolume]
[UnionVolume]
0.0<opB<0.04
[UnionVolume]
[UnionVolume]
0.0<opB<0.09
[UnionVolume]
[UnionVolume]
0.0<opB<0.16
[UnionVolume]
[UnionVolume]
0.0<opB<0.25
[UnionVolume]
[UnionVolume]

When doing the same for the original 3-state potential I get 
A
0.0<opA<0.04
[UnionVolume]
all states except A
B
C
[UnionVolume]
0.0<opA<0.09
[UnionVolume]
[UnionVolume]
0.0<opA<0.16
[UnionVolume]
[UnionVolume]
0.0<opA<0.25
[UnionVolume]
[UnionVolume]
0.0<opB<0.04
[UnionVolume]
all states except B
[UnionVolume]
0.0<opB<0.09
[UnionVolume]
[UnionVolume]
0.0<opB<0.16
[UnionVolume]
[UnionVolume]
0.0<opB<0.25
[UnionVolume]
[UnionVolume]
0.0<opC<0.04
[UnionVolume]
all states except C
[UnionVolume]
0.0<opC<0.09
[UnionVolume]
[UnionVolume]
0.0<opC<0.16
[UnionVolume]
[UnionVolume]
0.0<opC<0.25
[UnionVolume]
[UnionVolume]

It thus looks like only 1 state (B) is stored. I don't understand this. Do you?
 The only difference is that I took out the state C in the new notebook and created only an MSTIS network for A and B. Everything in the tps_bootstrap seems fine.  


In general, I have to say the way that the storage of volumes works is very unclear.  I expected a hierachachal definition e.g. a list of the interface ensembles. Instead this is a very unclear list of something, which I have no idea about. 
This should not be the way we should set up the initialisation . Why can't we have a function that prints the hierarchical set up of all states and interfaces? I put up an new issue about this.

**Comment by dwhswenson** [comment]
Are you doing `storage.sync_all()` at the end of your bootstrap script? What happens if you try to do `storage.find('A')` at the end of the your bootstrap script?

If your bootstrap is following the same path as the `mstis_bootstrap` notebook, check the storage counts. At the end of the `mstis_bootstrap` and the beginning of the `mstis` notebooks, there are a few lines that print the number of various items known in storage. These should be the same, and they should be reasonable: If you only save the last sample in each interface ensemble, then the number of samples should be equal to the number of interfaces you created.

> In general, I have to say the way that the storage of volumes works is very unclear.  I expected a hierachachal definition

In the netCDF file itself, the hierarchy is flattened, and we save a lot of objects that are intermediates and might not be relevant to the user. That what you see when you look directly at the storage as above. As discussed in #364, the more user-friendly view comes from the `print` function. However, that won't tell you about what is saved to disk, only what is in memory.

My guess is that the problem here has to do with a difference between what is on disk and what is in memory. In our setup, saving something to disk is a two-step process. I think @jhprinz is using names that match the netCDF names, although I think the names can lead to confusion. The two step process is:

1. `save` : stage into a cache area
2. `sync` : write to disk (we use `sync_all` for this)

I'm used to thinking "save" means "write to disk." Here, it does not. You need to "sync" for that.

**Comment by dwhswenson** [comment]
.... wait, I think I see what might be happening. You can't rename an object, and I think "A" gets a different name before it gets named "A". @jhprinz : this is an interesting side effect in storage that you might think about. Sometimes the same object in implementation has two different meanings from a user-facing perspective, and therefore might want two different names.

Here's what I suspect:

A TIS ensemble from `stateA` to `stateB` is defined with the last frame in `stateA or stateB`. In the multiple state picture, the last frame is in `any_state`, which we implement as `stateA or any_state_other_than_A`. This is to avoid checking `stateA | stateA | stateB | stateC`, which checks whether a frame is in `stateA` twice. So we find all the states other than the initial state, and join them together into a state called "all states except $statename"

If there are only two states, "all states except B" ***is*** "A". I notice that the list of volumes starts with "all states except B".

I think can put together a way around this that doesn't check the initial state twice, but it'll take some coding. I'll put up a PR sometime this weekend. In the very short run, @bolhuis, try loading "all states except B" instead of "A", and go from there.

**Comment by dwhswenson** [comment]
> You can't rename an object

Hmm... this might be incorrect. It looks like you can't rename an object *after* it has been saved. Same basic problem (one object, two names), but the issue might be that "A" got renamed to "all states except B", instead starting at "all states except B" and not getting renamed.

In that case, another solution would be to rename it right before saving. Set `stateA.name = "A"` right before you call the first `storage.save`, and it should fix everything.

**Comment by bolhuis** [comment]
Guys, I think that the error is already in the MSTIS network definition. See also issue #364. 
It is now clear that when after the bootstrap I do 

stateB1= storage.volumes.find('A')[0]
print stateB1

there euslt is

**Comment by dwhswenson** [comment]
Read my comments above.

**Comment by bolhuis** [comment]
I am currently reading......

"If there are only two states, "all states except B" is "A". I notice that the list of volumes starts with "all states except B".

I think can put together a way around this that doesn't check the initial state twice, but it'll take some coding. I'll put up a PR sometime this weekend. In the very short run, @bolhuis, try loading "all states except B" instead of "A", and go from there."

This seems indeed the case.

**Comment by dwhswenson** [comment]
Fix is ready -- just waiting for @jhprinz to look it over. (Sentence fragments because I'm writing this on phone)

**Comment by bolhuis** [comment]
It is still strange that the stateename in the bootstap is originally A, but gets changed in the mstis creation. I followed your advise and used

mstis = paths.MSTISNetwork([
    (stateA, interfacesA, "A", opA),
    (stateB, interfacesB, "B", opB)
])
stateA.name = "A"
print mstis

this results in :
Multiple State TIS Network:
TISTransition: Out B
B -> B or A
Interface: 0.0<opB<0.04
Interface: 0.0<opB<0.09
Interface: 0.0<opB<0.16
TISTransition: Out A
A -> A or B
Interface: 0.0<opA<0.04
Interface: 0.0<opA<0.09
Interface: 0.0<opA<0.16

So this problem seems to be solved!

However, there seems to be a follow up problem:

loading the states seems now find:
print len(old_store.volumes)
for volume in old_store.volumes:
    print volume.name

gives:

26
A
0.0<opA<0.04
[UnionVolume]
B
[UnionVolume]
0.0<opA<0.09
[UnionVolume]
[UnionVolume]
0.0<opA<0.16
[UnionVolume]
[UnionVolume]
0.0<opA<0.25
[UnionVolume]
[UnionVolume]
0.0<opB<0.04
[UnionVolume]
[UnionVolume]
0.0<opB<0.09
[UnionVolume]
[UnionVolume]
0.0<opB<0.16
[UnionVolume]
[UnionVolume]
0.0<opB<0.25
[UnionVolume]
[UnionVolume]

However, now defining the mstis network seems to have trouble:


mstis = paths.MSTISNetwork([
    (stateA, interfacesA, "A", opA),
    (stateB, interfacesB, "B", opB),
])

ValueError                                Traceback (most recent call last)
<ipython-input-10-29d781cae51d> in <module>()
      1 mstis = paths.MSTISNetwork([
      2     (stateA, interfacesA, "A", opA),
----> 3     (stateB, interfacesB, "B", opB),
      4 ])

/Users/bolhuis/git/openpathsampling/openpathsampling/analysis/network.pyc in __init__(self, trans_info)
    129             self.special_ensembles = {}
    130             self.from_state = {}
--> 131             self.build_fromstate_transitions(trans_info)
    132 
    133         self._sampling_transitions = self.from_state.values()

/Users/bolhuis/git/openpathsampling/openpathsampling/analysis/network.pyc in build_fromstate_transitions(self, trans_info)
    188             other_states = states[:state_index]+states[state_index+1:]
    189             union_others = paths.volume.join_volumes(other_states)
--> 190             union_others.name = "all states except " + str(name)
    191 
    192             this_trans = paths.TISTransition(

/Users/bolhuis/git/openpathsampling/openpathsampling/base.pyc in name(self, name)
    213         if self._name_fixed:
    214             raise ValueError('Objects cannot be renamed to "%s" after is has been saved, it is already named "%s"' % (
--> 215                 name, self._name))
    216         else:
    217             self._name = name

ValueError: Objects cannot be renamed to "all states except A" after is has been saved, it is already named "B"


which seems to be the reverse error of the original problem. The states have the correct names, but  network wants to changes them to "all states except A"

**Comment by dwhswenson** [comment]
Yeah, that's exactly the case: *Now* it's the issue that you can't rename an object after it has been stored (anything you load from storage has, of course, been stored!)

All of this should be fixed by #366. Then you won't need to do the hack to change the name before saving, and none of this should be a problem.

I don't know if @jhprinz has any time this weekend; if he doesn't have a chance to merge it before I get up tomorrow, I'll just merge it myself. (We normally try to make sure that whatever one of us writes, the other one reviews, just as a matter of principle. But this case is literally one extra line of actual code, and since the tests pass, it should be fine.)
