### ISSUE TITLE
failing of paths.CV_Function

### ISSUE THREAD

**Issue by bolhuis** [choderalab/openpathsampling#365]
The move_strategies_and_schemes notebook has been broken.
Here is the an error in the setup of the network.

# real fast setup of a small network
from openpathsampling import VolumeFactory as vf
cvA = paths.CV_Function(name="xA", fcn=lambda s : s.xyz[0][0])
cvB = paths.CV_Function(name="xB", fcn=lambda s : -s.xyz[0][0])
stateA = paths.CVRangeVolume(cvA, float("-inf"), -0.5)
stateB = paths.CVRangeVolume(cvB, float("-inf"), -0.5)
interfacesA = vf.CVRangeVolumeSet(cvA, float("-inf"), [-0.5, -0.3, -0.1, 0.0])
interfacesB = vf.CVRangeVolumeSet(cvB, float("-inf"), [-0.5, -0.3, -0.1, 0.0])
network = paths.MSTISNetwork([
    (stateA, interfacesA, "A", cvA),
    (stateB, interfacesB, "B", cvB)
])

TypeError                                 Traceback (most recent call last)
<ipython-input-6-116b8dd88384> in <module>()
      1 # real fast setup of a small network
      2 from openpathsampling import VolumeFactory as vf
----> 3 cvA = paths.CV_Function(name="xA", fcn=lambda s : s.xyz[0][0])
      4 cvB = paths.CV_Function(name="xB", fcn=lambda s : -s.xyz[0][0])
      5 stateA = paths.CVRangeVolume(cvA, float("-inf"), -0.5)

TypeError: __init__() takes at least 3 arguments (2 given)

It looks like  the CV_function has changed. Is this true?

**Comment by dwhswenson** [comment]
In #300, the argument name `fcn` changed to `f`. That is the source of this error. But I think you have an outdated version of the notebook: the [version currently in master (from commit 41b3140)](https://github.com/choderalab/openpathsampling/blob/master/examples/ipython/move_strategies_and_schemes.ipynb) has the correct syntax.

**Comment by jchodera** [comment]
You may need to merge in the master version with the magic incantation
```bash
git fetch upstream
git merge upstream/master
git push origin
```

**Comment by bolhuis** [comment]
OK, I am a bit backward in this git thing. I don't know what happend. 
I moved the old move_strategies_and_schemes.ipynb file, and re-pulled. This already solved the problem. Should I still do what John suggests?

**Comment by dwhswenson** [comment]
@jchodera's approach is the trick if you have things set up as a fork; but I think *you* may have it set up as a direct clone of the choderalab version. You can check this with the command (within a directory in the repository):

```
git remote -v
```

If you have a fork, you should see fetch and push for `origin` (which will have your username in the path) and fetch and push for `upstream` (which will have `choderalab`) in the path.

If you have a direct clone of the repo, you'll just have pointers to the `choderalab` version, and I think they'll be named `origin`.

The fork approach is better when you're adding to the code. The direct clone is easier if you're treating the repo as read-only, but want to stay up to date on the most recent code. @bolhuis, it might be worth setting up a fork-based approach. Instructions and explanation here: https://help.github.com/articles/fork-a-repo/

In any case, closing this issue since it sounds like it the immediate problem has been fixed.
