### ISSUE TITLE
Error in loading AnalysisStorage with self-created class

### ISSUE THREAD

**Issue by Asagodi** [choderalab/openpathsampling#381]
When trying to do the analysis for a simulation with a self created class, I get an error for not updating the storable classes. Is it possible to update before creating the storage?

https://gist.github.com/Asagodi/c55ac48864feab8f82d5#file-3c_h_04-ipynb
Error:
----> 1 storage = paths.storage.AnalysisStorage("3C_H_4_data.nc")
ValueError: Cannot create obj of class "LBISplitXY".
Class is not registered as creatable! You might have to define
the class locally and call update_storable_classes() on your storage.

**Comment by jhprinz** [comment]
Sure, I did not think of this. Of course this should be called automatically! Thanks for the tip.

**Comment by Asagodi** [comment]
Why is the integrator necessary for loading the dataset anyway?

**Comment by dwhswenson** [comment]
> Why is the integrator necessary for loading the dataset actually?

When OPS reloads an object, it (usually) completely recreates the object. For example, when you load a `MoveScheme`, it recreates the `PathMover`s within. If a `PathMover` involves a `DynamicsEngine` (as, for example, shooting moves do), it will rebuild that `DynamicsEngine`. The `DynamicsEngine` includes the integrator, which is then rebuilt.

One option would be to make these "lazy-loading," so that, for example, the integrator only gets built if it is actually needed. However, it is more important that the object be restorable, because you might want to use your original file as a restart point for a later calculation. Lazy-loading would hide the problem, but wouldn't really fix it.

> Also, is this solved in the version after the #371 merge?

No, I wouldn't think so. #371 only dealt with the interface to network objects. It was primarily a cosmetic change.

**Comment by jhprinz** [comment]
I just checked that the update is called when a store is opened. For performae reasons this is not done everytime you try to load something. Hence the `storage.update_storable_classes()` to do that when you create the class _after_ you opened the store. If this error still occurs then I am not sure what happened. 

I realized in your notebook that you reuse the same variable `storage` all the time and open new storages. Doing so will implicitly close the storage at some unknown point in the future, when the garbage collector decides to clean up the storage or when you restart. So it is good practise to close a storage if you do not want to use it anymore. 

At some point you ran the `AnalysisStorage` to get the faster caching. If you want to do that directly without opening a new storage you can have the same effect of caching when running.
```
paths.storage.AnalysisStorage.cache_for_analysis(storage)
```
and it will change the caching behaviour and cache all existing results.

There is another funny thing I should investiage. The AnalysisCaching does not cache the engines. So there must be another object that requires knowing about the engine. This might solve your problem. Because then the engine is not cached it does not matter that is cannot be loaded as long as you do not try to restart or continue your simulations.

**Comment by dwhswenson** [comment]
> The AnalysisCaching does not cache the engines. So there must be another object that requires knowing about the engine.

I expect it is ShootMover, MinusMover, etc.

**Comment by jhprinz** [comment]
Just checked. It is the MinusMovers.

It there a reason to store the engine with the PathMover?
I would remove this if it is not required and add this back when we add the engine to samples.

**Comment by dwhswenson** [comment]
The engine needs to be known by the EngineMover subclasses. Otherwise you can't do the dynamics.

**Comment by jhprinz** [comment]
Exactly but this is set usually by the user using 
```
paths.EngineMover.engine = ...
```
I figure that this is only stored for MinusMovers because the minus move assigns self.engine while the other use the class property. Since PathMover use the default storage behavior they will store the engine with it. 

The default is to store all variables in `__dict__` that do not start with an underscore `_`. An engine is one in this case. When it is loaded then the reconstruction will call the constructor with all variables that are listet in the constructor signature (for minus movers this is `def __init__(self, minus_ensemble, innermost_ensembles)` and hence engine will not be put in there. Afterwards (if the private class variable `_restore_non_initial_attr` is set to True (default) all other variables will be set explicitely after construction. So the reconstruction runs `new_mover.engine = ...` to set all these variables.

I think we can safely remove this as long as the minus does not need to know the engine itself and only require that the used shooters/extenders have an engine.

**Comment by dwhswenson** [comment]
Does this mean that a user can't just restart a simulation without explicitly assigning the engine? Or that a user can easily make the mistake of explicitly assigning the ***wrong*** engine when restarting/continuing a simulation? This seems dangerous to me.

**Comment by jhprinz** [comment]
Not sure if I understand what you mean.

Right now the assignment of engine to all PathMovers works using the class property
```
paths.EngineMover.engine = my_engine
```
After setting this all moves will use this engine. And this is what you have to do when you load from a file and want to restart. Let's say you store two engines, then it is not clear which one you want to use.

When you create a new engine the default is that it is set to be used for moving as the new default.

I agree that this current behaviour is not ideal, but I think we decided against passing the engine to all movers explicitely. This would be the clearer solution, but mean that you create movers per engine. 

Against being dangerous speaks that if you load and there is only one engine nothing can go wrong.

**Comment by dwhswenson** [comment]
> Let's say you store two engines, then it is not clear which one you want to use.

You make 2 engines, and 2 pathmovers. Mover A uses Engine A. Mover B uses engine B. Everything gets stored.

To me, it seems that when you reload the mover, you want it associated with the same engine. I don't think it makes sense to require the user to manually set it, if there's a way around that. Importantly, if you're using the mover as a way of checking which samples to combine in some analysis, ***the engine must be the same***. Otherwise you're combining paths from different engines, which is wrong. So either we have to check that every snapshot came from the same engine, or we have to check that the same engine was used for the path mover. Seems more efficient to check the mover.

This could really be a problem if you had a couple engines for different temperatures, and got them mixed up. I think that's a realistic case to watch out for.

It wouldn't be hard to only use instance variables for the engine, but to default that to the class variable. I think that would solve this. And yes, you'd have to load the engine when you load the mover, but is that a bad thing? You should be able to load the engine.

**Comment by jhprinz** [comment]
> To me, it seems that when you reload the mover, you want it associated with the same engine. I don't think it makes sense to require the user to manually set it, if there's a way around that. Importantly, if you're using the mover as a way of checking which samples to combine in some analysis, the engine must be the same. Otherwise you're combining paths from different engines, which is wrong. So either we have to check that every snapshot came from the same engine, or we have to check that the same engine was used for the path mover. Seems more efficient to check the mover.

I agree. But this is not how this is implemented at the time. For minus this worked by accident, but not for any other mover. 

If we agree then I will issue a PR that fixes this. Do we want to be able to set the mover directly in a Pathmover? I think that should be the case. And if it is `None` or unset (default) it will use the default in `EngineMover.engine` as the fallback. If this one is also empty or `None` we throw an exception `No engine specified`.

Does that should resonable? Or does that interfere with MoveSchemes?

**Comment by dwhswenson** [comment]
@Asagodi : if you're using a post-#300 version of the code with your notebook as given in the gist, you're mixing old and new styles of OPS class hierarchy. Most likely, you have a bunch of .pyc files left in your OPS directory (in particular, to_dict.pyc) which are giving you access to deleted classes. I'd recommend an `rm *pyc` in that directory.

As of now, you need to import `StorableNamedObject` from `openpathsampling.base` instead of OPSNamed from to_dict, and changing OPSNamed to StorableNamedObject throughout. (@jhprinz, is this changing in one of the upcoming PRs? I thought that `openpathsampling.base` was moving as part of a directory restructure.)

At least, making these changes (and a couple other updates of `scheme.move_decision_tree()` to `scheme`) meant that I could start the analysis section of your notebook without problems.

**Comment by jhprinz** [comment]
base has already moved to `openpathsampling.netcdfplus.base`.

To use it import
```
from openpathsampling.netcdfplus import StorableObject
```

**Comment by jhprinz** [comment]
Everything necessary for making storage in general possible is now in `netcdfplus` and everything that is OPS specific storage is still in `storage`.

**Comment by dwhswenson** [comment]
> base has already moved to openpathsampling.netcdfplus.base

Ah, thanks -- I thought that was the case, but apparently I hadn't pulled those changes into my ugly_srtis branch. Anyway, I think that's the solution to Abel's problem.

**Comment by jhprinz** [comment]
Yes, correct. If the integrator is not subclassed from StorableObject then it will not be recognized as being loadable!

**Comment by jhprinz** [comment]
Can this be closed? Any objections?

**Comment by jhprinz** [comment]
I think this is solved. Since there were no objections I close this for now.
