### ISSUE TITLE
Keyerror when loading file.nc with Analysisstorage

### ISSUE THREAD

**Issue by Asagodi** [choderalab/openpathsampling#410]
After I updated OPS (yesterday), I got an error when trying to load a file for analysis. Is there something that changed in the method for the storage or the analysis?

https://gist.github.com/Asagodi/f0c698d2719ed4403b21#file-4d_analysis30-copy2-ipynb

**Comment by dwhswenson** [comment]
The version you are running is not up-to-date with the GitHub version. This can be seen from the error you get, which points to source code:

```
/home/asagodi/anaconda/lib/python2.7/site-packages/openpathsampling-0.0.1a0-py2.7.egg/openpathsampling/netcdfplus/netcdfplus.pyc in create_variable_delegate(self, var_name)
    738         """
    739         if var_name not in self.vars:
--> 740             var = self.vars[var_name]
```

The current version (from commit 7b2767f) of `netcdfplus/netcdfplus.py`, function `create_variable_delegate` [can be seen here](https://github.com/choderalab/openpathsampling/blob/7b2767f33ee919529484d3eb2103acff3a108bcf/openpathsampling/netcdfplus/netcdfplus.py#L734). Note, in particular, the current line 741, which is `var = self.variables[var_name]`. This differs from your line 740, which raises the error. (The version in your code *should* be nonsense, actually. Not sure how that ever got into a live version of the code. It basically says "if this is going to raise a `KeyError`, let's force the `KeyError`." Looks to me like a commit from the middle of a renaming process.)

How to fix this depends on how you installed OPS. It looks to me like you have two versions of OPS on your system: one that has been installed by `conda` at `/home/asagodi/anaconda/lib/python2.7/site-packages/` and one (probably from GitHub) at `/home/asagodi/openpathsampling`. My suggestion is to uninstall the `conda` version, and to install OPS from your copy of the git repository using [`python setup.py develop`](http://stackoverflow.com/questions/19048732/python-setup-py-develop-vs-install) (or, nearly equivalently, `pip install -e .`, which is what I use).

Since the code is rapidly changing, this allows you to use `conda`'s convenient install process to get all the pre-requisites, but then to use a version with direct access to the git repository for day-to-day work, instead of the `conda` version.

This may also be the reason you were seeing behavior in #390 that didn't match the behavior of the properly updated code: if the source code that you'd updated wasn't the code that is actually used by Python, then the update wouldn't have changed anything.

**Comment by Asagodi** [comment]
I am sorry, I uploaded the wrong file. I tried to understand what was happening and changed some things and did not safe after I set everything back.

After I uninstalled the conda version of OPS and installed the github version, I still get the same keyerror. 

https://gist.github.com/Asagodi/63c42210e11cf9587da8#file-4d_analysis30-copy2-ipynb

**Comment by jhprinz** [comment]
It seems that you generated the `.nc` file with an older version and the new loading is not compatible. Did you regenerate the data with the new storage or would that be too difficult?

It is possible to retrieve all data, but that is not trivial. The underlying problem is that in the new version there is an additional list that stores what object types are actually stored. in the previous version this was hardcoded in the loading routine, so this is much more flexible to future additions. 

If rerunning the generation scripts with the updated version does not fix the problem please let me know. Then we have a serious bug!

**Comment by jhprinz** [comment]
I think with adding #420 and a way to identify if the installed version is uptodate we can close this, yes?

**Comment by Asagodi** [comment]
Rerunning helped, the problem indeed was the difference in old and new .nc files.

**Comment by jhprinz** [comment]
Thanks. Closing.
