### ISSUE TITLE
AttributeError: 'ToySnapshot' object has no attribute 'configuration'

### ISSUE THREAD

**Issue by Asagodi** [choderalab/openpathsampling#411]
I am trying to set up a MISTIS calculation for 4 states. Which transitions should I choose for initial_transitions and input_transitions?

Furthermore, I don understand why I the configuration of a ToySnapshot is need.

https://gist.github.com/Asagodi/cb5a16b9172094928ea5#file-4_mistis_boot-ipynb

**Comment by dwhswenson** [comment]
> Which transitions should I choose for initial_transitions and input_transitions?

The `input_transitions` are the transitions (state pairs) that you want to study. For MISTIS, the transition is described using a tuple with `(initial_state, interfaces, order_parameter, final_state)` -- this is just a shorthand to create the actual transition object. Note that the *actual* sampling ensembles need to know about *all* the states -- this shorthand makes it so we can create the correct sampling ensembles algorithmically, without the user having to specify the excluded states for each ensemble.

For the quick version, think of the tuple this way: each tuple represents a rate from `initial_state` to `final_state` calculated using `interfaces` (which are defined by `order_parameter`).

With that background, this part looks wrong to me:

```python
mistis = paths.MISTISNetwork([
    (stateA, interfacesAB, opX, stateD),
    (stateA, interfacesAC, opY, stateD),
    (stateD, interfacesDC, opXprime, stateA),
    (stateD, interfacesDB, opYprime, stateA)
])
```

This says that you want to look at the following rates:

* `stateA`->`stateD` using `interfacesAB`
* `stateA`->`stateD` using `interfacesAC`
* `stateD`->`stateA` using `interfacesDC`
* `stateD`->`stateA` using `interfacesDB`

This is the sort of set-up you might do if you were looking at reaction with two channels, and you wanted to compare the two channels. But I'm pretty sure that won't be very efficient with these interfaces on this system. What are you trying to do? Do you only want to look at A->D / D->A transitions? (In which case, you probably need a better order parameter.) Are you trying to look at *all* 12 transitions in the system? (In which case, you'll need 12 individual transitions.)

Also: I'm not sure what you meant by `initial_transitions` (at least, that doesn't show up in the current source code). It might have been a previous name for something that I decided to rename more clearly later.

> Furthermore, I don understand why I the configuration of a ToySnapshot is need.

The error you list in the title of this issue isn't in the gist you posted, so I can't help much with that. However, in general, an `openpathsampling.Configuration` is a container for the positions (as well as a few other things). I know that @jhprinz has been making some changes to the way snapshots are structured, so the need for that may have changed (again, if you were loading from an old file, it might not be compatible). He may be able to tell you more.

**Comment by Asagodi** [comment]
Here is the right file with the error:
https://gist.github.com/Asagodi/14453f7424ab02e237d7#file-4_mistis_boot-ipynb
Also, when I tried to redo the calculations to generate an up-to-date .nc file, I got the same error:
https://gist.github.com/Asagodi/b5caab92e5cdae3e097e

**Comment by dwhswenson** [comment]
Change all instances of `paths.Snapshot` to `paths.ToySnapshot`. That's for the `template` and for the `initA`, `initB`, etc. Also, remove `kinetic_energy` and `potential_energy` attributes from the `template` (these do not exist for `ToySnapshot`).

As of #384 different engines have different classes for snapshots. The standard `paths.Snapshot` can be used for typical MD (Gromacs, OpenMM, LAMMPS, etc). The `ToyEngine` has its own kind of snapshot, a `ToySnapshot`. We split up snapshot types because other engines (e.g., for ab initio MD or semiclassical MD), might need to store different information. Hypothetically, OPS could be used for non-chemical systems (e.g., models of financial markets, or studies of data transfer in computer networks), which would then have *very* different data fields.

@jhprinz : Engines should probably log a warning if trying to set `current_snapshot` to a snapshot that isn't of the correct type. I say "log warning" because that will give text -- with red background in an ipynb -- to say "this isn't normal", but won't stop running in case the user actually intended to do that. Think of it like type casting: really, we prefer that users explicitly re-type the snapshot if re-using between engines, but we can allow them to implicitly cast. However, implicit casts should be warned against, because of exactly this problem. We also might look at improving the implicit cast behavior.

**Comment by dwhswenson** [comment]
@Asagodi : You will have to re-run from the bootstrapping, of course (which is the file I was looking at when I said to change those things).

**Comment by jhprinz** [comment]
: @jhprinz : Engines should probably log a warning if trying to set current_snapshot to a snapshot that isn't of the correct type. I say "log warning" because that will give text -- with red background in an ipynb -- to say "this isn't normal", but won't stop running in case the user actually intended to do that. Think of it like type casting: really, we prefer that users explicitly re-type the snapshot if re-using between engines, but we can allow them to implicitly cast. However, implicit casts should be warned against, because of exactly this problem. We also might look at improving the implicit cast behavior.

Thanks for finding that. Yes, we changed it so that we can adapt the complexity of the snapshot to the type of simulation that we want to do. I will make a PR to throw a warning if you use the non-intended snapshot type for an engine.

**Comment by Asagodi** [comment]
Thank you, my calculations are running again!

@dwhswenson : The idea was to compare the rates calculated with MISTIS for the A/D transition to (RE)TIS calculations. So my main interest would be only those transitions. 
Looking at just one transition would thus be equivalent with two separate TIS calculations? 
The two different transitions I actually want to compare is diagonally straight from A to D and a transition which uses first one coordinate and then the other (avoiding the barrier in the middle).

**Comment by jhprinz** [comment]
Goot to hear that it works. I was worried for a little while. I hope that these breaking changes will be almost a thing of the past. We will let you know if that will happen again.
