### ISSUE TITLE
LockedMoveScheme is not storable

### ISSUE THREAD

**Issue by jhprinz** [choderalab/openpathsampling#418]
I just tried to create a simple `LockedMoveScheme` with a super simple Mover inside. It can be used but not stored, because it complains about non set `.mover` attribute. I am not sure why that is but I assume there is a reason. 

Btw. Do we want to have a possibility to just use a PathSampling without a scheme? For this non-standard test cases it seems unnecessary to use the LockedScheme in-between. We could just have a shortcut for this.

**Comment by dwhswenson** [comment]
> I just tried to create a simple `LockedMoveScheme` with a super simple Mover inside. It can be used but not stored, because it complains about non set .mover attribute. I am not sure why that is but I assume there is a reason.

I also don't know why this would be. `LockedMoveScheme` doesn't have a `.mover` attribute. It does have a `.movers` (plural) attribute, inherited from `MoveScheme`. Is that the problem?

> Btw. Do we want to have a possibility to just use a PathSampling without a scheme?

This is the purpose of `LockedMoveScheme`. It lets the user give a specific root mover, and wraps that in a move scheme object.

To use PathSampling without a `MoveScheme` would mean:
* give up all the analysis that comes with the `MoveScheme` object
* make the PathSampling object more complicated by managing two different initialization approaches
* require documentation to cover two possibilities for many situations ("if you used a `MoveScheme`, do this; if not, then you need to do this longer process to get the same information")

I think a wrapper class like `LockedMoveScheme`, which adds exactly one line to any code using it (or less, actually, since it only needs to be called inside the PathSampling parameter list), is about as simple as it gets.

> For this non-standard test cases it seems unnecessary to use the LockedScheme in-between. We could just have a shortcut for this.

How common is this case? My thought was that the one-liner of `scheme=paths.LockedMoveScheme(root_mover=my_root, network=my_network)` ***is*** the short cut. One extra line that handles everything to make the less common case (manual preparation of the move scheme) support all the conveniences of the common case.

Keep in mind that all the analysis is based on having a stored `network` and a stored `scheme`. If you use that one-liner, `PathSampling` will automatically save the scheme and network. Otherwise, you have to save those manually.

**Comment by dwhswenson** [comment]
UPDATE: Created a minimal test on my own. I assume you did mean `.movers`, plural? (Since that's the error I got.) This is because there's no way for the code to figure out how to set the `scheme.movers` dictionary algorithmically. The `scheme.movers` dictionary is a dictionary `{ move_type : list_of_movers }` which maps move type strings (e.g., 'shooting', 'repex', 'minus') to the list of movers of that type. The user can customize it so that, for example, there can be more than one "type" of shooting move (useful for analysis). These define the "mover groups" used in analysis. 

The problem is that `MoveScheme` assumes that you've already defined that when saving. `LockedMoveScheme` doesn't technically require the `.movers` to be set (although setting it makes more thing possible in analysis). In any case, I think it is a relatively easy fix. Should have it done later today.
